export const HISTORICAL_FIGURES_SUGGESTIONS = [
  'Marie Curie',
  'Nikola Tesla',
  'Joan of Arc',
  'William Shakespeare',
  'Julius Caesar',
  'Alexander the Great',
  'Genghis Khan',
  'Queen Elizabeth I',
  'Martin Luther King Jr.',
  'Nelson Mandela',
  'Mahatma Gandhi',
  'Winston Churchill',
  'Franklin D. Roosevelt',
  'Abraham Lincoln',
  'George Washington',
  'Napoleon Bonaparte',
  'Catherine the Great',
  'Peter the Great',
  'Sun Tzu',
  'Hatshepsut',
  'Ramesses II',
  'Tutankhamun',
  'Frida Kahlo',
  'Vincent van Gogh',
  'Pablo Picasso',
  'Michelangelo',
  'Rembrandt',
  'Wolfgang Amadeus Mozart',
  'Ludwig van Beethoven',
  'Johann Sebastian Bach',
  'Pyotr Ilyich Tchaikovsky',
  'Jane Austen',
  'Charles Dickens',
  'Mark Twain',
  'Leo Tolstoy',
  'Fyodor Dostoevsky',
  'Virginia Woolf',
  'George Orwell',
  'Mary Shelley',
  'Edgar Allan Poe',
  'Homer',
  'Hypatia',
  'Pythagoras',
  'Euclid',
  'Archimedes',
  'Rosalind Franklin',
  'Gregor Mendel',
  'Charles Darwin',
  'Galileo Galilei',
  'Isaac Newton',
  'Albert Einstein',
  'Stephen Hawking',
  'Carl Sagan',
  'Grace Hopper',
  'Alan Turing',
  'Tim Berners-Lee',
  'Steve Jobs',
  'Bill Gates',
  'Henry Ford',
  'The Wright Brothers',
  'Thomas Edison',
  'Alexander Graham Bell',
  'James Watt',
  'Marco Polo',
  'Christopher Columbus',
  'Ferdinand Magellan',
  'Vasco da Gama',
  'Ibn Battuta',
  'Zheng He',
  'Leif Erikson',
  'Amelia Earhart',
  'Neil Armstrong',
  'Yuri Gagarin',
  'Sacagawea',
  'Pocahontas',
  'Sitting Bull',
  'Geronimo',
  'Harriet Tubman',
  'Frederick Douglass',
  'Susan B. Anthony',
  'Rosa Parks',
  'Simone de Beauvoir',
  'Mary Wollstonecraft',
  'Karl Marx',
  'Friedrich Nietzsche',
  'Immanuel Kant',
  'John Locke',
  'Voltaire',
  'Jean-Jacques Rousseau',
  'René Descartes',
  'Niccolò Machiavelli',
  'Mansa Musa',
  'Saladin',
  'Shaka Zulu',
  'Akbar the Great',
  'Ashoka the Great',
  'Qin Shi Huang',
  'Confucius',
  'Laozi',
];
